export interface EmojiEntry {
    emoji: string;
    keywords: string[];
}

export interface EmojiCategory {
    name: string;
    icon: string;
    emojis: EmojiEntry[];
}

export const emojiCategories: EmojiCategory[] = [
    {
        name: "Smileys",
        icon: "😀",
        emojis: [
            { emoji: "😀", keywords: ["grinning", "happy", "smile"] },
            { emoji: "😃", keywords: ["smiley", "happy"] },
            { emoji: "😄", keywords: ["smile", "happy", "laugh"] },
            { emoji: "😁", keywords: ["grin", "happy"] },
            { emoji: "😆", keywords: ["laugh", "happy"] },
            { emoji: "😅", keywords: ["sweat", "laugh", "nervous"] },
            { emoji: "🤣", keywords: ["rofl", "laugh", "rolling"] },
            { emoji: "😂", keywords: ["joy", "laugh", "tears"] },
            { emoji: "🙂", keywords: ["slight", "smile"] },
            { emoji: "😉", keywords: ["wink", "flirt"] },
            { emoji: "😊", keywords: ["blush", "smile", "shy"] },
            { emoji: "😇", keywords: ["innocent", "angel", "halo"] },
            { emoji: "🥰", keywords: ["love", "hearts", "smile"] },
            { emoji: "😍", keywords: ["love", "heart", "eyes"] },
            { emoji: "🤩", keywords: ["star", "excited", "amazing"] },
            { emoji: "😘", keywords: ["kiss", "love"] },
            { emoji: "😗", keywords: ["kiss"] },
            { emoji: "😚", keywords: ["kiss", "blush"] },
            { emoji: "😙", keywords: ["kiss", "smile"] },
            { emoji: "🥲", keywords: ["tear", "sad", "smile"] },
            { emoji: "😋", keywords: ["yummy", "tongue", "taste"] },
            { emoji: "😛", keywords: ["tongue", "playful"] },
            { emoji: "😜", keywords: ["wink", "tongue", "crazy"] },
            { emoji: "🤪", keywords: ["crazy", "zany", "wild"] },
            { emoji: "😝", keywords: ["tongue", "squint"] },
            { emoji: "🤑", keywords: ["money", "rich"] },
            { emoji: "🤗", keywords: ["hug", "warm"] },
            { emoji: "🤭", keywords: ["giggle", "quiet"] },
            { emoji: "🤫", keywords: ["quiet", "shh", "silence"] },
            { emoji: "🤔", keywords: ["thinking", "hmm", "wonder"] },
            { emoji: "🫡", keywords: ["salute", "respect"] },
            { emoji: "🤐", keywords: ["zip", "quiet", "mute"] },
            { emoji: "🤨", keywords: ["skeptical", "raised", "brow"] },
            { emoji: "😐", keywords: ["neutral", "meh"] },
            { emoji: "😑", keywords: ["expressionless", "blank"] },
            { emoji: "😶", keywords: ["silent", "no", "mouth"] },
            { emoji: "🫥", keywords: ["dotted", "invisible"] },
            { emoji: "😏", keywords: ["smirk", "smug"] },
            { emoji: "😒", keywords: ["unamused", "bored"] },
            { emoji: "🙄", keywords: ["eye", "roll", "annoyed"] },
            { emoji: "😬", keywords: ["grimace", "awkward"] },
            { emoji: "😮‍💨", keywords: ["exhale", "sigh", "relief"] },
            { emoji: "🤥", keywords: ["lie", "pinocchio"] },
            { emoji: "😌", keywords: ["relieved", "peaceful"] },
            { emoji: "😔", keywords: ["sad", "pensive"] },
            { emoji: "😪", keywords: ["sleepy", "tired"] },
            { emoji: "🤤", keywords: ["drool", "hungry"] },
            { emoji: "😴", keywords: ["sleep", "zzz"] },
            { emoji: "😷", keywords: ["mask", "sick", "covid"] },
            { emoji: "🤒", keywords: ["sick", "fever", "thermometer"] },
            { emoji: "🤕", keywords: ["bandage", "hurt", "injury"] },
            { emoji: "🤢", keywords: ["nausea", "sick", "green"] },
            { emoji: "🤮", keywords: ["vomit", "sick"] },
            { emoji: "🥵", keywords: ["hot", "heat"] },
            { emoji: "🥶", keywords: ["cold", "freezing"] },
            { emoji: "🥴", keywords: ["drunk", "dizzy", "woozy"] },
            { emoji: "😵", keywords: ["dizzy", "dead"] },
            { emoji: "😵‍💫", keywords: ["spiral", "dizzy"] },
            { emoji: "🤯", keywords: ["mind", "blown", "exploding"] },
            { emoji: "🤠", keywords: ["cowboy", "hat"] },
            { emoji: "🥳", keywords: ["party", "celebrate", "birthday"] },
            { emoji: "🥸", keywords: ["disguise", "nose", "glasses"] },
            { emoji: "😎", keywords: ["cool", "sunglasses"] },
            { emoji: "🤓", keywords: ["nerd", "glasses", "smart"] },
            { emoji: "🧐", keywords: ["monocle", "inspect", "curious"] },
            { emoji: "😕", keywords: ["confused"] },
            { emoji: "🫤", keywords: ["diagonal", "mouth", "unsure"] },
            { emoji: "😟", keywords: ["worried"] },
            { emoji: "🙁", keywords: ["frown", "sad"] },
            { emoji: "😮", keywords: ["open", "mouth", "surprised"] },
            { emoji: "😯", keywords: ["hushed", "surprised"] },
            { emoji: "😲", keywords: ["astonished", "shocked"] },
            { emoji: "😳", keywords: ["flushed", "embarrassed"] },
            { emoji: "🥺", keywords: ["pleading", "puppy", "eyes"] },
            { emoji: "🥹", keywords: ["holding", "tears", "emotional"] },
            { emoji: "😦", keywords: ["frown", "open", "mouth"] },
            { emoji: "😧", keywords: ["anguished"] },
            { emoji: "😨", keywords: ["fearful", "scared"] },
            { emoji: "😰", keywords: ["anxious", "sweat"] },
            { emoji: "😥", keywords: ["sad", "relieved"] },
            { emoji: "😢", keywords: ["cry", "tear"] },
            { emoji: "😭", keywords: ["sob", "cry", "loud"] },
            { emoji: "😱", keywords: ["scream", "horror", "fear"] },
            { emoji: "😖", keywords: ["confounded"] },
            { emoji: "😣", keywords: ["persevere"] },
            { emoji: "😞", keywords: ["disappointed"] },
            { emoji: "😓", keywords: ["downcast", "sweat"] },
            { emoji: "😩", keywords: ["weary", "tired"] },
            { emoji: "😫", keywords: ["tired", "exhausted"] },
            { emoji: "🥱", keywords: ["yawn", "tired", "bored"] },
            { emoji: "😤", keywords: ["angry", "huff", "triumph"] },
            { emoji: "😡", keywords: ["angry", "red", "face"] },
            { emoji: "😠", keywords: ["angry"] },
            { emoji: "🤬", keywords: ["swear", "curse", "angry"] },
            { emoji: "😈", keywords: ["devil", "evil", "smile"] },
            { emoji: "👿", keywords: ["devil", "angry"] },
            { emoji: "💀", keywords: ["skull", "dead", "death"] },
            { emoji: "☠️", keywords: ["skull", "crossbones", "danger"] },
            { emoji: "💩", keywords: ["poop", "shit"] },
            { emoji: "🤡", keywords: ["clown"] },
            { emoji: "👹", keywords: ["ogre", "monster"] },
            { emoji: "👻", keywords: ["ghost", "spooky"] },
            { emoji: "👽", keywords: ["alien", "ufo"] },
            { emoji: "🤖", keywords: ["robot", "bot"] },
            { emoji: "😺", keywords: ["cat", "smile"] },
            { emoji: "😸", keywords: ["cat", "grin"] },
            { emoji: "😹", keywords: ["cat", "joy"] },
            { emoji: "😻", keywords: ["cat", "heart", "eyes"] },
            { emoji: "😼", keywords: ["cat", "wry"] },
            { emoji: "😽", keywords: ["cat", "kiss"] },
            { emoji: "🙀", keywords: ["cat", "weary"] },
            { emoji: "😿", keywords: ["cat", "cry"] },
            { emoji: "😾", keywords: ["cat", "angry"] },
            { emoji: "❤️", keywords: ["heart", "love", "red"] },
            { emoji: "🧡", keywords: ["heart", "orange"] },
            { emoji: "💛", keywords: ["heart", "yellow"] },
            { emoji: "💚", keywords: ["heart", "green"] },
            { emoji: "💙", keywords: ["heart", "blue"] },
            { emoji: "💜", keywords: ["heart", "purple"] },
            { emoji: "🖤", keywords: ["heart", "black"] },
            { emoji: "🤍", keywords: ["heart", "white"] },
            { emoji: "🤎", keywords: ["heart", "brown"] },
            { emoji: "💔", keywords: ["broken", "heart", "sad"] },
            { emoji: "❤️‍🔥", keywords: ["heart", "fire", "passion"] },
            { emoji: "💕", keywords: ["hearts", "love"] },
            { emoji: "💞", keywords: ["revolving", "hearts"] },
            { emoji: "💓", keywords: ["heartbeat", "love"] },
            { emoji: "💗", keywords: ["growing", "heart"] },
            { emoji: "💖", keywords: ["sparkling", "heart"] },
            { emoji: "💘", keywords: ["cupid", "love", "arrow"] },
            { emoji: "💝", keywords: ["gift", "heart"] },
            { emoji: "💯", keywords: ["hundred", "perfect", "100"] },
            { emoji: "💢", keywords: ["anger", "mad"] },
            { emoji: "💥", keywords: ["boom", "explosion", "collision"] },
            { emoji: "💫", keywords: ["dizzy", "star"] },
            { emoji: "💦", keywords: ["splash", "water"] },
            { emoji: "💨", keywords: ["wind", "dash", "fast"] },
            { emoji: "🕳️", keywords: ["hole"] },
            { emoji: "💤", keywords: ["sleep", "zzz"] },
        ]
    },
    {
        name: "People",
        icon: "👋",
        emojis: [
            { emoji: "👋", keywords: ["wave", "hello", "hi", "bye"] },
            { emoji: "🤚", keywords: ["raised", "back", "hand"] },
            { emoji: "🖐️", keywords: ["hand", "five", "spread"] },
            { emoji: "✋", keywords: ["hand", "stop", "high"] },
            { emoji: "🖖", keywords: ["vulcan", "spock", "star"] },
            { emoji: "🫱", keywords: ["rightwards", "hand"] },
            { emoji: "🫲", keywords: ["leftwards", "hand"] },
            { emoji: "👌", keywords: ["ok", "perfect"] },
            { emoji: "🤌", keywords: ["pinched", "italian"] },
            { emoji: "🤏", keywords: ["pinching", "small"] },
            { emoji: "✌️", keywords: ["peace", "victory", "two"] },
            { emoji: "🤞", keywords: ["crossed", "fingers", "luck"] },
            { emoji: "🫰", keywords: ["hand", "heart", "love"] },
            { emoji: "🤟", keywords: ["love", "you", "rock"] },
            { emoji: "🤘", keywords: ["rock", "metal", "horns"] },
            { emoji: "🤙", keywords: ["call", "shaka", "hang"] },
            { emoji: "👈", keywords: ["point", "left", "this"] },
            { emoji: "👉", keywords: ["point", "right", "that"] },
            { emoji: "👆", keywords: ["point", "up", "above"] },
            { emoji: "👇", keywords: ["point", "down", "below"] },
            { emoji: "☝️", keywords: ["point", "up", "one"] },
            { emoji: "🫵", keywords: ["point", "you"] },
            { emoji: "👍", keywords: ["thumbs", "up", "like", "yes", "good", "approve"] },
            { emoji: "👎", keywords: ["thumbs", "down", "dislike", "no", "bad"] },
            { emoji: "✊", keywords: ["fist", "power"] },
            { emoji: "👊", keywords: ["fist", "bump", "punch"] },
            { emoji: "🤛", keywords: ["fist", "left"] },
            { emoji: "🤜", keywords: ["fist", "right"] },
            { emoji: "👏", keywords: ["clap", "applause", "bravo"] },
            { emoji: "🙌", keywords: ["raising", "hands", "celebration"] },
            { emoji: "🫶", keywords: ["heart", "hands", "love"] },
            { emoji: "👐", keywords: ["open", "hands"] },
            { emoji: "🤲", keywords: ["palms", "together"] },
            { emoji: "🤝", keywords: ["handshake", "deal", "agreement"] },
            { emoji: "🙏", keywords: ["pray", "please", "thanks", "namaste"] },
            { emoji: "✍️", keywords: ["write", "pen"] },
            { emoji: "💅", keywords: ["nail", "polish", "fabulous"] },
            { emoji: "🤳", keywords: ["selfie", "camera"] },
            { emoji: "💪", keywords: ["muscle", "strong", "power"] },
            { emoji: "🦾", keywords: ["mechanical", "arm", "cyborg"] },
            { emoji: "🦿", keywords: ["mechanical", "leg"] },
            { emoji: "🦵", keywords: ["leg"] },
            { emoji: "🦶", keywords: ["foot"] },
            { emoji: "👂", keywords: ["ear", "hear", "listen"] },
            { emoji: "🦻", keywords: ["ear", "hearing", "aid"] },
            { emoji: "👃", keywords: ["nose", "smell"] },
            { emoji: "🧠", keywords: ["brain", "smart", "mind"] },
            { emoji: "🫀", keywords: ["heart", "anatomy"] },
            { emoji: "🫁", keywords: ["lungs", "breathe"] },
            { emoji: "🦷", keywords: ["tooth"] },
            { emoji: "🦴", keywords: ["bone"] },
            { emoji: "👀", keywords: ["eyes", "see", "look", "watch"] },
            { emoji: "👁️", keywords: ["eye"] },
            { emoji: "👅", keywords: ["tongue", "taste"] },
            { emoji: "👄", keywords: ["lips", "mouth", "kiss"] },
            { emoji: "🫦", keywords: ["biting", "lip"] },
            { emoji: "👶", keywords: ["baby", "child"] },
            { emoji: "🧒", keywords: ["child", "kid"] },
            { emoji: "👦", keywords: ["boy"] },
            { emoji: "👧", keywords: ["girl"] },
            { emoji: "🧑", keywords: ["person"] },
            { emoji: "👨", keywords: ["man"] },
            { emoji: "👩", keywords: ["woman"] },
            { emoji: "🧓", keywords: ["older", "person"] },
            { emoji: "👴", keywords: ["old", "man"] },
            { emoji: "👵", keywords: ["old", "woman"] },
            { emoji: "🙍", keywords: ["frown", "person"] },
            { emoji: "🙎", keywords: ["pouting", "person"] },
            { emoji: "🙅", keywords: ["no", "gesture", "stop"] },
            { emoji: "🙆", keywords: ["ok", "gesture"] },
            { emoji: "💁", keywords: ["person", "tipping", "hand"] },
            { emoji: "🙋", keywords: ["raising", "hand", "me"] },
            { emoji: "🧏", keywords: ["deaf", "person"] },
            { emoji: "🙇", keywords: ["bow", "sorry", "respect"] },
            { emoji: "🤦", keywords: ["facepalm", "oops"] },
            { emoji: "🤷", keywords: ["shrug", "dunno", "whatever"] },
            { emoji: "👮", keywords: ["police", "officer"] },
            { emoji: "🕵️", keywords: ["detective", "spy", "investigate"] },
            { emoji: "💂", keywords: ["guard"] },
            { emoji: "🥷", keywords: ["ninja", "stealth"] },
            { emoji: "👷", keywords: ["construction", "worker"] },
            { emoji: "🫅", keywords: ["crown", "royal", "king"] },
            { emoji: "🤴", keywords: ["prince"] },
            { emoji: "👸", keywords: ["princess"] },
            { emoji: "👳", keywords: ["turban", "person"] },
            { emoji: "👲", keywords: ["cap", "person"] },
            { emoji: "🧕", keywords: ["headscarf", "hijab"] },
            { emoji: "🤵", keywords: ["tuxedo", "groom", "wedding"] },
            { emoji: "👰", keywords: ["bride", "veil", "wedding"] },
            { emoji: "🤰", keywords: ["pregnant", "baby"] },
            { emoji: "🫄", keywords: ["pregnant", "person"] },
            { emoji: "🤱", keywords: ["breastfeeding"] },
            { emoji: "👼", keywords: ["baby", "angel"] },
            { emoji: "🎅", keywords: ["santa", "christmas"] },
            { emoji: "🤶", keywords: ["mrs", "claus", "christmas"] },
            { emoji: "🦸", keywords: ["superhero"] },
            { emoji: "🦹", keywords: ["supervillain"] },
            { emoji: "🧙", keywords: ["mage", "wizard", "magic"] },
            { emoji: "🧚", keywords: ["fairy", "magic"] },
            { emoji: "🧛", keywords: ["vampire"] },
            { emoji: "🧜", keywords: ["mermaid", "merperson"] },
            { emoji: "🧝", keywords: ["elf"] },
            { emoji: "🧞", keywords: ["genie"] },
            { emoji: "🧟", keywords: ["zombie"] },
            { emoji: "🧌", keywords: ["troll"] },
            { emoji: "💆", keywords: ["massage", "relax"] },
            { emoji: "💇", keywords: ["haircut"] },
            { emoji: "🚶", keywords: ["walk", "person"] },
            { emoji: "🧍", keywords: ["standing"] },
            { emoji: "🧎", keywords: ["kneeling"] },
            { emoji: "🏃", keywords: ["run", "running"] },
            { emoji: "💃", keywords: ["dance", "woman"] },
            { emoji: "🕺", keywords: ["dance", "man"] },
            { emoji: "👫", keywords: ["couple", "hold", "hands"] },
            { emoji: "👬", keywords: ["couple", "men"] },
            { emoji: "👭", keywords: ["couple", "women"] },
            { emoji: "💏", keywords: ["kiss", "couple"] },
            { emoji: "💑", keywords: ["couple", "heart", "love"] },
            { emoji: "👪", keywords: ["family"] },
            { emoji: "🗣️", keywords: ["speaking", "talk", "say"] },
            { emoji: "👤", keywords: ["user", "person", "profile"] },
            { emoji: "👥", keywords: ["users", "people", "group"] },
            { emoji: "🫂", keywords: ["hug", "people"] },
        ]
    },
    {
        name: "Animals",
        icon: "🐱",
        emojis: [
            { emoji: "🐶", keywords: ["dog", "puppy", "pet"] },
            { emoji: "🐱", keywords: ["cat", "kitten", "pet"] },
            { emoji: "🐭", keywords: ["mouse"] },
            { emoji: "🐹", keywords: ["hamster"] },
            { emoji: "🐰", keywords: ["rabbit", "bunny"] },
            { emoji: "🦊", keywords: ["fox"] },
            { emoji: "🐻", keywords: ["bear"] },
            { emoji: "🐼", keywords: ["panda"] },
            { emoji: "🐻‍❄️", keywords: ["polar", "bear"] },
            { emoji: "🐨", keywords: ["koala"] },
            { emoji: "🐯", keywords: ["tiger"] },
            { emoji: "🦁", keywords: ["lion"] },
            { emoji: "🐮", keywords: ["cow"] },
            { emoji: "🐷", keywords: ["pig"] },
            { emoji: "🐸", keywords: ["frog"] },
            { emoji: "🐵", keywords: ["monkey"] },
            { emoji: "🙈", keywords: ["see", "no", "evil", "monkey"] },
            { emoji: "🙉", keywords: ["hear", "no", "evil", "monkey"] },
            { emoji: "🙊", keywords: ["speak", "no", "evil", "monkey"] },
            { emoji: "🐔", keywords: ["chicken"] },
            { emoji: "🐧", keywords: ["penguin"] },
            { emoji: "🐦", keywords: ["bird"] },
            { emoji: "🐤", keywords: ["baby", "chick"] },
            { emoji: "🦆", keywords: ["duck"] },
            { emoji: "🦅", keywords: ["eagle"] },
            { emoji: "🦉", keywords: ["owl"] },
            { emoji: "🦇", keywords: ["bat"] },
            { emoji: "🐺", keywords: ["wolf"] },
            { emoji: "🐗", keywords: ["boar", "pig"] },
            { emoji: "🐴", keywords: ["horse"] },
            { emoji: "🦄", keywords: ["unicorn"] },
            { emoji: "🐝", keywords: ["bee", "honey"] },
            { emoji: "🪱", keywords: ["worm"] },
            { emoji: "🐛", keywords: ["bug", "caterpillar"] },
            { emoji: "🦋", keywords: ["butterfly"] },
            { emoji: "🐌", keywords: ["snail"] },
            { emoji: "🐞", keywords: ["ladybug"] },
            { emoji: "🐜", keywords: ["ant"] },
            { emoji: "🪰", keywords: ["fly"] },
            { emoji: "🪲", keywords: ["beetle"] },
            { emoji: "🪳", keywords: ["cockroach"] },
            { emoji: "🦟", keywords: ["mosquito"] },
            { emoji: "🦗", keywords: ["cricket"] },
            { emoji: "🕷️", keywords: ["spider"] },
            { emoji: "🦂", keywords: ["scorpion"] },
            { emoji: "🐢", keywords: ["turtle"] },
            { emoji: "🐍", keywords: ["snake"] },
            { emoji: "🦎", keywords: ["lizard"] },
            { emoji: "🦖", keywords: ["dinosaur", "t-rex"] },
            { emoji: "🦕", keywords: ["dinosaur", "sauropod"] },
            { emoji: "🐙", keywords: ["octopus"] },
            { emoji: "🦑", keywords: ["squid"] },
            { emoji: "🦐", keywords: ["shrimp"] },
            { emoji: "🦞", keywords: ["lobster"] },
            { emoji: "🦀", keywords: ["crab"] },
            { emoji: "🐡", keywords: ["blowfish", "puffer"] },
            { emoji: "🐠", keywords: ["fish", "tropical"] },
            { emoji: "🐟", keywords: ["fish"] },
            { emoji: "🐬", keywords: ["dolphin"] },
            { emoji: "🐳", keywords: ["whale", "spouting"] },
            { emoji: "🐋", keywords: ["whale"] },
            { emoji: "🦈", keywords: ["shark"] },
            { emoji: "🐊", keywords: ["crocodile"] },
            { emoji: "🐅", keywords: ["tiger"] },
            { emoji: "🐆", keywords: ["leopard"] },
            { emoji: "🦓", keywords: ["zebra"] },
            { emoji: "🦍", keywords: ["gorilla"] },
            { emoji: "🦧", keywords: ["orangutan"] },
            { emoji: "🐘", keywords: ["elephant"] },
            { emoji: "🦛", keywords: ["hippo"] },
            { emoji: "🦏", keywords: ["rhino"] },
            { emoji: "🐪", keywords: ["camel"] },
            { emoji: "🐫", keywords: ["camel", "two", "hump"] },
            { emoji: "🦒", keywords: ["giraffe"] },
            { emoji: "🦘", keywords: ["kangaroo"] },
            { emoji: "🦬", keywords: ["bison"] },
            { emoji: "🐃", keywords: ["water", "buffalo"] },
            { emoji: "🐂", keywords: ["ox"] },
            { emoji: "🐄", keywords: ["cow"] },
            { emoji: "🐎", keywords: ["horse", "racing"] },
            { emoji: "🐖", keywords: ["pig"] },
            { emoji: "🐏", keywords: ["ram"] },
            { emoji: "🐑", keywords: ["sheep", "ewe"] },
            { emoji: "🦙", keywords: ["llama"] },
            { emoji: "🐐", keywords: ["goat"] },
            { emoji: "🦌", keywords: ["deer"] },
            { emoji: "🐕", keywords: ["dog"] },
            { emoji: "🐩", keywords: ["poodle"] },
            { emoji: "🦮", keywords: ["guide", "dog"] },
            { emoji: "🐕‍🦺", keywords: ["service", "dog"] },
            { emoji: "🐈", keywords: ["cat"] },
            { emoji: "🐈‍⬛", keywords: ["black", "cat"] },
            { emoji: "🪶", keywords: ["feather"] },
            { emoji: "🐓", keywords: ["rooster"] },
            { emoji: "🦃", keywords: ["turkey"] },
            { emoji: "🦚", keywords: ["peacock"] },
            { emoji: "🦜", keywords: ["parrot"] },
            { emoji: "🦢", keywords: ["swan"] },
            { emoji: "🦩", keywords: ["flamingo"] },
            { emoji: "🕊️", keywords: ["dove", "peace"] },
            { emoji: "🦤", keywords: ["dodo"] },
            { emoji: "🪺", keywords: ["nest", "eggs"] },
            { emoji: "🌸", keywords: ["cherry", "blossom", "spring"] },
            { emoji: "💮", keywords: ["white", "flower"] },
            { emoji: "🏵️", keywords: ["rosette"] },
            { emoji: "🌹", keywords: ["rose", "flower"] },
            { emoji: "🥀", keywords: ["wilted", "flower"] },
            { emoji: "🌺", keywords: ["hibiscus"] },
            { emoji: "🌻", keywords: ["sunflower"] },
            { emoji: "🌼", keywords: ["blossom"] },
            { emoji: "🌷", keywords: ["tulip"] },
            { emoji: "🌱", keywords: ["seedling", "grow", "plant"] },
            { emoji: "🪴", keywords: ["potted", "plant"] },
            { emoji: "🌲", keywords: ["evergreen", "tree"] },
            { emoji: "🌳", keywords: ["deciduous", "tree"] },
            { emoji: "🌴", keywords: ["palm", "tree"] },
            { emoji: "🌵", keywords: ["cactus"] },
            { emoji: "🌾", keywords: ["rice", "grain"] },
            { emoji: "🌿", keywords: ["herb", "green"] },
            { emoji: "☘️", keywords: ["shamrock"] },
            { emoji: "🍀", keywords: ["clover", "four", "leaf", "luck"] },
            { emoji: "🍁", keywords: ["maple", "leaf", "fall"] },
            { emoji: "🍂", keywords: ["fallen", "leaf", "autumn"] },
            { emoji: "🍃", keywords: ["leaf", "wind"] },
            { emoji: "🪹", keywords: ["empty", "nest"] },
            { emoji: "🍄", keywords: ["mushroom"] },
        ]
    },
    {
        name: "Food",
        icon: "🍕",
        emojis: [
            { emoji: "🍇", keywords: ["grapes", "fruit", "wine"] },
            { emoji: "🍈", keywords: ["melon"] },
            { emoji: "🍉", keywords: ["watermelon"] },
            { emoji: "🍊", keywords: ["orange", "fruit"] },
            { emoji: "🍋", keywords: ["lemon", "sour"] },
            { emoji: "🍌", keywords: ["banana"] },
            { emoji: "🍍", keywords: ["pineapple"] },
            { emoji: "🥭", keywords: ["mango"] },
            { emoji: "🍎", keywords: ["apple", "red"] },
            { emoji: "🍏", keywords: ["apple", "green"] },
            { emoji: "🍐", keywords: ["pear"] },
            { emoji: "🍑", keywords: ["peach", "butt"] },
            { emoji: "🍒", keywords: ["cherries"] },
            { emoji: "🍓", keywords: ["strawberry"] },
            { emoji: "🫐", keywords: ["blueberries"] },
            { emoji: "🥝", keywords: ["kiwi"] },
            { emoji: "🍅", keywords: ["tomato"] },
            { emoji: "🫒", keywords: ["olive"] },
            { emoji: "🥥", keywords: ["coconut"] },
            { emoji: "🥑", keywords: ["avocado"] },
            { emoji: "🍆", keywords: ["eggplant", "aubergine"] },
            { emoji: "🥔", keywords: ["potato"] },
            { emoji: "🥕", keywords: ["carrot"] },
            { emoji: "🌽", keywords: ["corn", "maize"] },
            { emoji: "🌶️", keywords: ["pepper", "hot", "spicy"] },
            { emoji: "🫑", keywords: ["bell", "pepper"] },
            { emoji: "🥦", keywords: ["broccoli"] },
            { emoji: "🧄", keywords: ["garlic"] },
            { emoji: "🧅", keywords: ["onion"] },
            { emoji: "🥜", keywords: ["peanuts"] },
            { emoji: "🫘", keywords: ["beans"] },
            { emoji: "🌰", keywords: ["chestnut"] },
            { emoji: "🍞", keywords: ["bread"] },
            { emoji: "🥐", keywords: ["croissant"] },
            { emoji: "🥖", keywords: ["baguette", "bread"] },
            { emoji: "🫓", keywords: ["flatbread", "naan"] },
            { emoji: "🥨", keywords: ["pretzel"] },
            { emoji: "🥯", keywords: ["bagel"] },
            { emoji: "🥞", keywords: ["pancakes"] },
            { emoji: "🧇", keywords: ["waffle"] },
            { emoji: "🧀", keywords: ["cheese"] },
            { emoji: "🍖", keywords: ["meat", "bone"] },
            { emoji: "🍗", keywords: ["chicken", "leg"] },
            { emoji: "🥩", keywords: ["steak", "meat"] },
            { emoji: "🥓", keywords: ["bacon"] },
            { emoji: "🍔", keywords: ["hamburger", "burger"] },
            { emoji: "🍟", keywords: ["fries", "french", "fries"] },
            { emoji: "🍕", keywords: ["pizza"] },
            { emoji: "🌭", keywords: ["hotdog", "hot", "dog"] },
            { emoji: "🥪", keywords: ["sandwich"] },
            { emoji: "🌮", keywords: ["taco"] },
            { emoji: "🌯", keywords: ["burrito"] },
            { emoji: "🫔", keywords: ["tamale"] },
            { emoji: "🥙", keywords: ["pita", "falafel"] },
            { emoji: "🧆", keywords: ["falafel"] },
            { emoji: "🥚", keywords: ["egg"] },
            { emoji: "🍳", keywords: ["cooking", "egg", "frying"] },
            { emoji: "🥘", keywords: ["stew", "pan"] },
            { emoji: "🍲", keywords: ["pot", "soup", "stew"] },
            { emoji: "🫕", keywords: ["fondue"] },
            { emoji: "🥣", keywords: ["bowl", "cereal", "soup"] },
            { emoji: "🥗", keywords: ["salad"] },
            { emoji: "🍿", keywords: ["popcorn"] },
            { emoji: "🧈", keywords: ["butter"] },
            { emoji: "🧂", keywords: ["salt"] },
            { emoji: "🥫", keywords: ["can", "preserves"] },
            { emoji: "🍱", keywords: ["bento", "box"] },
            { emoji: "🍘", keywords: ["rice", "cracker"] },
            { emoji: "🍙", keywords: ["rice", "ball", "onigiri"] },
            { emoji: "🍚", keywords: ["rice", "cooked"] },
            { emoji: "🍛", keywords: ["curry"] },
            { emoji: "🍜", keywords: ["noodle", "ramen", "soup"] },
            { emoji: "🍝", keywords: ["spaghetti", "pasta"] },
            { emoji: "🍠", keywords: ["sweet", "potato"] },
            { emoji: "🍢", keywords: ["oden"] },
            { emoji: "🍣", keywords: ["sushi"] },
            { emoji: "🍤", keywords: ["fried", "shrimp", "tempura"] },
            { emoji: "🍥", keywords: ["fish", "cake"] },
            { emoji: "🥮", keywords: ["moon", "cake"] },
            { emoji: "🍡", keywords: ["dango"] },
            { emoji: "🥟", keywords: ["dumpling"] },
            { emoji: "🥠", keywords: ["fortune", "cookie"] },
            { emoji: "🥡", keywords: ["takeout", "box"] },
            { emoji: "🦪", keywords: ["oyster"] },
            { emoji: "🍦", keywords: ["ice", "cream", "soft"] },
            { emoji: "🍧", keywords: ["shaved", "ice"] },
            { emoji: "🍨", keywords: ["ice", "cream"] },
            { emoji: "🍩", keywords: ["doughnut", "donut"] },
            { emoji: "🍪", keywords: ["cookie"] },
            { emoji: "🎂", keywords: ["birthday", "cake"] },
            { emoji: "🍰", keywords: ["cake", "shortcake"] },
            { emoji: "🧁", keywords: ["cupcake"] },
            { emoji: "🥧", keywords: ["pie"] },
            { emoji: "🍫", keywords: ["chocolate"] },
            { emoji: "🍬", keywords: ["candy"] },
            { emoji: "🍭", keywords: ["lollipop"] },
            { emoji: "🍮", keywords: ["pudding", "custard"] },
            { emoji: "🍯", keywords: ["honey"] },
            { emoji: "🍼", keywords: ["baby", "bottle"] },
            { emoji: "🥛", keywords: ["milk", "glass"] },
            { emoji: "☕", keywords: ["coffee", "hot", "beverage"] },
            { emoji: "🫖", keywords: ["teapot"] },
            { emoji: "🍵", keywords: ["tea", "green"] },
            { emoji: "🧃", keywords: ["juice", "box"] },
            { emoji: "🥤", keywords: ["cup", "straw", "drink"] },
            { emoji: "🧋", keywords: ["bubble", "tea", "boba"] },
            { emoji: "🍶", keywords: ["sake"] },
            { emoji: "🍺", keywords: ["beer"] },
            { emoji: "🍻", keywords: ["beers", "cheers"] },
            { emoji: "🥂", keywords: ["champagne", "clink", "cheers"] },
            { emoji: "🍷", keywords: ["wine", "glass"] },
            { emoji: "🥃", keywords: ["whisky", "bourbon"] },
            { emoji: "🍸", keywords: ["cocktail", "martini"] },
            { emoji: "🍹", keywords: ["tropical", "drink"] },
            { emoji: "🧊", keywords: ["ice", "cube"] },
            { emoji: "🍽️", keywords: ["dining", "plate"] },
            { emoji: "🥢", keywords: ["chopsticks"] },
        ]
    },
    {
        name: "Activities",
        icon: "⚽",
        emojis: [
            { emoji: "⚽", keywords: ["soccer", "football"] },
            { emoji: "🏀", keywords: ["basketball"] },
            { emoji: "🏈", keywords: ["football", "american"] },
            { emoji: "⚾", keywords: ["baseball"] },
            { emoji: "🥎", keywords: ["softball"] },
            { emoji: "🎾", keywords: ["tennis"] },
            { emoji: "🏐", keywords: ["volleyball"] },
            { emoji: "🏉", keywords: ["rugby"] },
            { emoji: "🥏", keywords: ["frisbee", "flying", "disc"] },
            { emoji: "🎱", keywords: ["pool", "billiards", "8"] },
            { emoji: "🪀", keywords: ["yoyo"] },
            { emoji: "🏓", keywords: ["ping", "pong", "table", "tennis"] },
            { emoji: "🏸", keywords: ["badminton"] },
            { emoji: "🏒", keywords: ["ice", "hockey"] },
            { emoji: "🏑", keywords: ["field", "hockey"] },
            { emoji: "🥍", keywords: ["lacrosse"] },
            { emoji: "🏏", keywords: ["cricket"] },
            { emoji: "🪃", keywords: ["boomerang"] },
            { emoji: "🥅", keywords: ["goal", "net"] },
            { emoji: "⛳", keywords: ["golf"] },
            { emoji: "🪁", keywords: ["kite"] },
            { emoji: "🏹", keywords: ["bow", "arrow", "archery"] },
            { emoji: "🎣", keywords: ["fishing"] },
            { emoji: "🤿", keywords: ["diving", "mask"] },
            { emoji: "🥊", keywords: ["boxing", "glove"] },
            { emoji: "🥋", keywords: ["martial", "arts", "karate", "judo"] },
            { emoji: "🎽", keywords: ["running", "shirt"] },
            { emoji: "⛸️", keywords: ["ice", "skate"] },
            { emoji: "🛷", keywords: ["sled"] },
            { emoji: "🎿", keywords: ["ski", "snow"] },
            { emoji: "⛷️", keywords: ["skier"] },
            { emoji: "🏂", keywords: ["snowboard"] },
            { emoji: "🪂", keywords: ["parachute"] },
            { emoji: "🏋️", keywords: ["weightlift", "gym"] },
            { emoji: "🤼", keywords: ["wrestling"] },
            { emoji: "🤸", keywords: ["cartwheel", "gymnastics"] },
            { emoji: "🤽", keywords: ["water", "polo"] },
            { emoji: "🤾", keywords: ["handball"] },
            { emoji: "🏌️", keywords: ["golfing"] },
            { emoji: "🏇", keywords: ["horse", "racing"] },
            { emoji: "🧘", keywords: ["yoga", "meditation"] },
            { emoji: "🏄", keywords: ["surfing"] },
            { emoji: "🏊", keywords: ["swimming"] },
            { emoji: "🤹", keywords: ["juggling"] },
            { emoji: "🎪", keywords: ["circus", "tent"] },
            { emoji: "🎭", keywords: ["theater", "drama", "performing", "arts"] },
            { emoji: "🎨", keywords: ["art", "paint", "palette"] },
            { emoji: "🎬", keywords: ["movie", "clapper", "film"] },
            { emoji: "🎤", keywords: ["microphone", "karaoke", "sing"] },
            { emoji: "🎧", keywords: ["headphone", "music", "audio"] },
            { emoji: "🎼", keywords: ["music", "notes", "score"] },
            { emoji: "🎵", keywords: ["music", "note"] },
            { emoji: "🎶", keywords: ["music", "notes"] },
            { emoji: "🎹", keywords: ["piano", "keyboard"] },
            { emoji: "🪘", keywords: ["drum"] },
            { emoji: "🥁", keywords: ["drum"] },
            { emoji: "🎷", keywords: ["saxophone"] },
            { emoji: "🎺", keywords: ["trumpet"] },
            { emoji: "🎸", keywords: ["guitar"] },
            { emoji: "🪕", keywords: ["banjo"] },
            { emoji: "🎻", keywords: ["violin"] },
            { emoji: "🎲", keywords: ["dice", "die", "random"] },
            { emoji: "♟️", keywords: ["chess", "pawn"] },
            { emoji: "🎯", keywords: ["target", "bullseye", "direct"] },
            { emoji: "🎳", keywords: ["bowling"] },
            { emoji: "🎮", keywords: ["game", "controller", "joystick"] },
            { emoji: "🕹️", keywords: ["joystick", "game"] },
            { emoji: "🎰", keywords: ["slot", "machine"] },
            { emoji: "🧩", keywords: ["puzzle", "piece"] },
            { emoji: "🪄", keywords: ["magic", "wand"] },
            { emoji: "🎁", keywords: ["gift", "present"] },
            { emoji: "🎀", keywords: ["ribbon", "bow"] },
            { emoji: "🎊", keywords: ["confetti", "ball"] },
            { emoji: "🎉", keywords: ["party", "celebration", "tada"] },
            { emoji: "🎈", keywords: ["balloon"] },
            { emoji: "🎗️", keywords: ["ribbon", "reminder"] },
            { emoji: "🏆", keywords: ["trophy", "winner", "champion"] },
            { emoji: "🏅", keywords: ["medal", "sports"] },
            { emoji: "🥇", keywords: ["gold", "medal", "first"] },
            { emoji: "🥈", keywords: ["silver", "medal", "second"] },
            { emoji: "🥉", keywords: ["bronze", "medal", "third"] },
            { emoji: "⚽", keywords: ["soccer"] },
            { emoji: "🎄", keywords: ["christmas", "tree"] },
            { emoji: "🎃", keywords: ["jack", "lantern", "halloween"] },
            { emoji: "🎆", keywords: ["fireworks"] },
            { emoji: "🎇", keywords: ["sparkler", "firework"] },
            { emoji: "✨", keywords: ["sparkles", "shine", "magic", "new"] },
            { emoji: "🎈", keywords: ["balloon", "party"] },
            { emoji: "🎋", keywords: ["tanabata", "tree"] },
            { emoji: "🎍", keywords: ["pine", "decoration"] },
            { emoji: "🎎", keywords: ["japanese", "dolls"] },
            { emoji: "🎏", keywords: ["carp", "streamer"] },
            { emoji: "🎐", keywords: ["wind", "chime"] },
            { emoji: "🎑", keywords: ["moon", "viewing"] },
            { emoji: "🧧", keywords: ["red", "envelope"] },
            { emoji: "🎀", keywords: ["ribbon"] },
            { emoji: "🎁", keywords: ["gift", "wrapped"] },
            { emoji: "🎗️", keywords: ["awareness", "ribbon"] },
            { emoji: "🎟️", keywords: ["ticket", "admission"] },
            { emoji: "🎫", keywords: ["ticket"] },
        ]
    },
    {
        name: "Travel",
        icon: "🚗",
        emojis: [
            { emoji: "🚗", keywords: ["car", "automobile"] },
            { emoji: "🚕", keywords: ["taxi"] },
            { emoji: "🚙", keywords: ["suv", "car"] },
            { emoji: "🚌", keywords: ["bus"] },
            { emoji: "🚎", keywords: ["trolleybus"] },
            { emoji: "🏎️", keywords: ["racing", "car"] },
            { emoji: "🚓", keywords: ["police", "car"] },
            { emoji: "🚑", keywords: ["ambulance"] },
            { emoji: "🚒", keywords: ["fire", "engine", "truck"] },
            { emoji: "🚐", keywords: ["minibus", "van"] },
            { emoji: "🛻", keywords: ["pickup", "truck"] },
            { emoji: "🚚", keywords: ["truck", "delivery"] },
            { emoji: "🚛", keywords: ["articulated", "lorry"] },
            { emoji: "🚜", keywords: ["tractor"] },
            { emoji: "🛵", keywords: ["scooter", "motorbike"] },
            { emoji: "🏍️", keywords: ["motorcycle", "motorbike"] },
            { emoji: "🚲", keywords: ["bicycle", "bike"] },
            { emoji: "🛴", keywords: ["kick", "scooter"] },
            { emoji: "🛹", keywords: ["skateboard"] },
            { emoji: "🛼", keywords: ["roller", "skate"] },
            { emoji: "🚏", keywords: ["bus", "stop"] },
            { emoji: "🛣️", keywords: ["motorway", "road"] },
            { emoji: "🛤️", keywords: ["railway", "track"] },
            { emoji: "⛽", keywords: ["fuel", "gas", "pump"] },
            { emoji: "🚨", keywords: ["siren", "police", "alarm"] },
            { emoji: "🚥", keywords: ["traffic", "light", "horizontal"] },
            { emoji: "🚦", keywords: ["traffic", "light", "vertical"] },
            { emoji: "🛑", keywords: ["stop", "sign"] },
            { emoji: "🚧", keywords: ["construction"] },
            { emoji: "⚓", keywords: ["anchor", "ship"] },
            { emoji: "🛟", keywords: ["ring", "buoy", "life"] },
            { emoji: "⛵", keywords: ["sailboat"] },
            { emoji: "🛶", keywords: ["canoe"] },
            { emoji: "🚤", keywords: ["speedboat"] },
            { emoji: "🛳️", keywords: ["ship", "passenger"] },
            { emoji: "⛴️", keywords: ["ferry"] },
            { emoji: "🛥️", keywords: ["motor", "boat"] },
            { emoji: "🚢", keywords: ["ship"] },
            { emoji: "✈️", keywords: ["airplane", "plane", "flight"] },
            { emoji: "🛩️", keywords: ["small", "airplane"] },
            { emoji: "🛫", keywords: ["takeoff", "flight"] },
            { emoji: "🛬", keywords: ["landing", "flight"] },
            { emoji: "🪂", keywords: ["parachute"] },
            { emoji: "💺", keywords: ["seat", "airplane"] },
            { emoji: "🚁", keywords: ["helicopter"] },
            { emoji: "🚟", keywords: ["suspension", "railway"] },
            { emoji: "🚠", keywords: ["mountain", "railway", "cable"] },
            { emoji: "🚡", keywords: ["aerial", "tramway", "gondola"] },
            { emoji: "🛰️", keywords: ["satellite"] },
            { emoji: "🚀", keywords: ["rocket", "launch", "space"] },
            { emoji: "🛸", keywords: ["ufo", "alien", "flying", "saucer"] },
            { emoji: "🚝", keywords: ["monorail"] },
            { emoji: "🚄", keywords: ["bullet", "train", "high", "speed"] },
            { emoji: "🚅", keywords: ["bullet", "train"] },
            { emoji: "🚈", keywords: ["light", "rail"] },
            { emoji: "🚂", keywords: ["locomotive", "train"] },
            { emoji: "🚆", keywords: ["train"] },
            { emoji: "🚇", keywords: ["metro", "subway"] },
            { emoji: "🚊", keywords: ["tram", "streetcar"] },
            { emoji: "🚉", keywords: ["station"] },
            { emoji: "🗺️", keywords: ["map", "world"] },
            { emoji: "🧭", keywords: ["compass", "navigation"] },
            { emoji: "🏔️", keywords: ["mountain", "snow"] },
            { emoji: "⛰️", keywords: ["mountain"] },
            { emoji: "🌋", keywords: ["volcano"] },
            { emoji: "🗻", keywords: ["mount", "fuji"] },
            { emoji: "🏕️", keywords: ["camping", "tent"] },
            { emoji: "🏖️", keywords: ["beach", "umbrella"] },
            { emoji: "🏜️", keywords: ["desert"] },
            { emoji: "🏝️", keywords: ["island", "desert"] },
            { emoji: "🏞️", keywords: ["national", "park"] },
            { emoji: "🏟️", keywords: ["stadium"] },
            { emoji: "🏛️", keywords: ["classical", "building"] },
            { emoji: "🏗️", keywords: ["building", "construction"] },
            { emoji: "🧱", keywords: ["brick"] },
            { emoji: "🪨", keywords: ["rock"] },
            { emoji: "🪵", keywords: ["wood", "log"] },
            { emoji: "🛖", keywords: ["hut"] },
            { emoji: "🏠", keywords: ["house", "home"] },
            { emoji: "🏡", keywords: ["house", "garden"] },
            { emoji: "🏢", keywords: ["office", "building"] },
            { emoji: "🏣", keywords: ["post", "office"] },
            { emoji: "🏥", keywords: ["hospital"] },
            { emoji: "🏦", keywords: ["bank"] },
            { emoji: "🏨", keywords: ["hotel"] },
            { emoji: "🏩", keywords: ["love", "hotel"] },
            { emoji: "🏪", keywords: ["store", "convenience"] },
            { emoji: "🏫", keywords: ["school"] },
            { emoji: "🏬", keywords: ["department", "store"] },
            { emoji: "🏭", keywords: ["factory"] },
            { emoji: "🏯", keywords: ["japanese", "castle"] },
            { emoji: "🏰", keywords: ["castle", "european"] },
            { emoji: "💒", keywords: ["wedding", "chapel"] },
            { emoji: "🗼", keywords: ["tower", "tokyo"] },
            { emoji: "🗽", keywords: ["statue", "liberty"] },
            { emoji: "⛪", keywords: ["church"] },
            { emoji: "🕌", keywords: ["mosque"] },
            { emoji: "🛕", keywords: ["hindu", "temple"] },
            { emoji: "🕍", keywords: ["synagogue"] },
            { emoji: "⛩️", keywords: ["shinto", "shrine"] },
            { emoji: "🕋", keywords: ["kaaba"] },
            { emoji: "⛲", keywords: ["fountain"] },
            { emoji: "⛺", keywords: ["tent"] },
            { emoji: "🌁", keywords: ["foggy", "bridge"] },
            { emoji: "🌃", keywords: ["night", "stars", "city"] },
            { emoji: "🏙️", keywords: ["cityscape"] },
            { emoji: "🌄", keywords: ["sunrise", "mountain"] },
            { emoji: "🌅", keywords: ["sunset"] },
            { emoji: "🌆", keywords: ["cityscape", "dusk"] },
            { emoji: "🌇", keywords: ["sunset", "city"] },
            { emoji: "🌉", keywords: ["bridge", "night"] },
            { emoji: "🎠", keywords: ["carousel"] },
            { emoji: "🛝", keywords: ["playground", "slide"] },
            { emoji: "🎡", keywords: ["ferris", "wheel"] },
            { emoji: "🎢", keywords: ["roller", "coaster"] },
        ]
    },
    {
        name: "Objects",
        icon: "💡",
        emojis: [
            { emoji: "⌚", keywords: ["watch", "time"] },
            { emoji: "📱", keywords: ["phone", "mobile", "smartphone"] },
            { emoji: "📲", keywords: ["call", "incoming"] },
            { emoji: "💻", keywords: ["laptop", "computer"] },
            { emoji: "⌨️", keywords: ["keyboard"] },
            { emoji: "🖥️", keywords: ["desktop", "computer", "monitor"] },
            { emoji: "🖨️", keywords: ["printer"] },
            { emoji: "🖱️", keywords: ["mouse", "computer"] },
            { emoji: "💾", keywords: ["floppy", "disk", "save"] },
            { emoji: "💿", keywords: ["cd", "disc"] },
            { emoji: "📀", keywords: ["dvd"] },
            { emoji: "🧮", keywords: ["abacus", "calculator"] },
            { emoji: "🎥", keywords: ["camera", "movie"] },
            { emoji: "🎞️", keywords: ["film", "frames"] },
            { emoji: "📽️", keywords: ["projector"] },
            { emoji: "📺", keywords: ["television", "tv"] },
            { emoji: "📷", keywords: ["camera", "photo"] },
            { emoji: "📸", keywords: ["camera", "flash", "photo"] },
            { emoji: "📹", keywords: ["video", "camera"] },
            { emoji: "📼", keywords: ["vhs", "videocassette"] },
            { emoji: "🔍", keywords: ["search", "magnify", "glass"] },
            { emoji: "🔎", keywords: ["search", "magnify"] },
            { emoji: "🕯️", keywords: ["candle"] },
            { emoji: "💡", keywords: ["light", "bulb", "idea"] },
            { emoji: "🔦", keywords: ["flashlight"] },
            { emoji: "🏮", keywords: ["lantern", "red"] },
            { emoji: "🪔", keywords: ["diya", "lamp"] },
            { emoji: "📔", keywords: ["notebook", "decorative"] },
            { emoji: "📕", keywords: ["book", "closed"] },
            { emoji: "📖", keywords: ["book", "open", "read"] },
            { emoji: "📗", keywords: ["book", "green"] },
            { emoji: "📘", keywords: ["book", "blue"] },
            { emoji: "📙", keywords: ["book", "orange"] },
            { emoji: "📚", keywords: ["books", "stack"] },
            { emoji: "📓", keywords: ["notebook"] },
            { emoji: "📒", keywords: ["ledger"] },
            { emoji: "📃", keywords: ["page", "curl"] },
            { emoji: "📜", keywords: ["scroll"] },
            { emoji: "📄", keywords: ["page", "document"] },
            { emoji: "📰", keywords: ["newspaper", "news"] },
            { emoji: "📑", keywords: ["bookmark", "tabs"] },
            { emoji: "🔖", keywords: ["bookmark"] },
            { emoji: "🏷️", keywords: ["label", "tag"] },
            { emoji: "💰", keywords: ["money", "bag"] },
            { emoji: "🪙", keywords: ["coin"] },
            { emoji: "💴", keywords: ["yen", "money"] },
            { emoji: "💵", keywords: ["dollar", "money"] },
            { emoji: "💶", keywords: ["euro", "money"] },
            { emoji: "💷", keywords: ["pound", "money"] },
            { emoji: "💸", keywords: ["money", "wings", "flying"] },
            { emoji: "💳", keywords: ["credit", "card"] },
            { emoji: "🧾", keywords: ["receipt"] },
            { emoji: "✉️", keywords: ["envelope", "mail", "email"] },
            { emoji: "📧", keywords: ["email", "mail"] },
            { emoji: "📥", keywords: ["inbox", "incoming"] },
            { emoji: "📤", keywords: ["outbox", "sent"] },
            { emoji: "📦", keywords: ["package", "box", "parcel"] },
            { emoji: "📫", keywords: ["mailbox", "closed"] },
            { emoji: "📬", keywords: ["mailbox", "open", "mail"] },
            { emoji: "📮", keywords: ["postbox"] },
            { emoji: "🗳️", keywords: ["ballot", "vote"] },
            { emoji: "✏️", keywords: ["pencil"] },
            { emoji: "✒️", keywords: ["pen", "nib"] },
            { emoji: "🖋️", keywords: ["fountain", "pen"] },
            { emoji: "🖊️", keywords: ["pen"] },
            { emoji: "🖌️", keywords: ["paintbrush"] },
            { emoji: "🖍️", keywords: ["crayon"] },
            { emoji: "📝", keywords: ["memo", "note", "write"] },
            { emoji: "📁", keywords: ["folder"] },
            { emoji: "📂", keywords: ["folder", "open"] },
            { emoji: "📅", keywords: ["calendar", "date"] },
            { emoji: "📆", keywords: ["calendar", "tear"] },
            { emoji: "🗓️", keywords: ["calendar", "spiral"] },
            { emoji: "📇", keywords: ["card", "index"] },
            { emoji: "📈", keywords: ["chart", "up", "growth"] },
            { emoji: "📉", keywords: ["chart", "down"] },
            { emoji: "📊", keywords: ["bar", "chart"] },
            { emoji: "📋", keywords: ["clipboard"] },
            { emoji: "📌", keywords: ["pin", "pushpin"] },
            { emoji: "📍", keywords: ["round", "pin", "location"] },
            { emoji: "📎", keywords: ["paperclip"] },
            { emoji: "🖇️", keywords: ["paperclips"] },
            { emoji: "📏", keywords: ["ruler", "straight"] },
            { emoji: "📐", keywords: ["triangle", "ruler"] },
            { emoji: "✂️", keywords: ["scissors", "cut"] },
            { emoji: "🗃️", keywords: ["card", "file", "box"] },
            { emoji: "🗄️", keywords: ["file", "cabinet"] },
            { emoji: "🗑️", keywords: ["trash", "delete", "bin"] },
            { emoji: "🔒", keywords: ["lock", "locked", "secure"] },
            { emoji: "🔓", keywords: ["unlock", "open"] },
            { emoji: "🔏", keywords: ["lock", "pen"] },
            { emoji: "🔐", keywords: ["lock", "key"] },
            { emoji: "🔑", keywords: ["key"] },
            { emoji: "🗝️", keywords: ["old", "key"] },
            { emoji: "🔨", keywords: ["hammer"] },
            { emoji: "🪓", keywords: ["axe"] },
            { emoji: "⛏️", keywords: ["pick"] },
            { emoji: "🔧", keywords: ["wrench", "tool"] },
            { emoji: "🔩", keywords: ["nut", "bolt"] },
            { emoji: "⚙️", keywords: ["gear", "settings"] },
            { emoji: "🪛", keywords: ["screwdriver"] },
            { emoji: "🧲", keywords: ["magnet"] },
            { emoji: "⚖️", keywords: ["balance", "scale", "justice"] },
            { emoji: "🔗", keywords: ["link", "chain"] },
            { emoji: "⛓️", keywords: ["chains"] },
            { emoji: "🧰", keywords: ["toolbox"] },
            { emoji: "🧪", keywords: ["test", "tube"] },
            { emoji: "🧫", keywords: ["petri", "dish"] },
            { emoji: "🧬", keywords: ["dna", "genetics"] },
            { emoji: "🔬", keywords: ["microscope"] },
            { emoji: "🔭", keywords: ["telescope"] },
            { emoji: "💉", keywords: ["syringe", "needle", "vaccine"] },
            { emoji: "🩸", keywords: ["drop", "blood"] },
            { emoji: "💊", keywords: ["pill", "medicine"] },
            { emoji: "🩹", keywords: ["adhesive", "bandage"] },
            { emoji: "🩺", keywords: ["stethoscope"] },
            { emoji: "🚪", keywords: ["door"] },
            { emoji: "🛗", keywords: ["elevator", "lift"] },
            { emoji: "🪞", keywords: ["mirror"] },
            { emoji: "🪟", keywords: ["window"] },
            { emoji: "🛏️", keywords: ["bed"] },
            { emoji: "🛋️", keywords: ["couch", "sofa"] },
            { emoji: "🪑", keywords: ["chair"] },
            { emoji: "🚽", keywords: ["toilet"] },
            { emoji: "🚿", keywords: ["shower"] },
            { emoji: "🛁", keywords: ["bathtub"] },
            { emoji: "🪒", keywords: ["razor"] },
            { emoji: "🧴", keywords: ["lotion", "bottle"] },
            { emoji: "🧷", keywords: ["safety", "pin"] },
            { emoji: "🧹", keywords: ["broom", "sweep"] },
            { emoji: "🧺", keywords: ["basket"] },
            { emoji: "🧻", keywords: ["toilet", "paper"] },
            { emoji: "🪣", keywords: ["bucket"] },
            { emoji: "🧼", keywords: ["soap"] },
            { emoji: "🫧", keywords: ["bubbles"] },
            { emoji: "🪥", keywords: ["toothbrush"] },
            { emoji: "🧽", keywords: ["sponge"] },
            { emoji: "🧯", keywords: ["fire", "extinguisher"] },
        ]
    },
    {
        name: "Symbols",
        icon: "🔣",
        emojis: [
            { emoji: "❤️", keywords: ["heart", "red", "love"] },
            { emoji: "🧡", keywords: ["orange", "heart"] },
            { emoji: "💛", keywords: ["yellow", "heart"] },
            { emoji: "💚", keywords: ["green", "heart"] },
            { emoji: "💙", keywords: ["blue", "heart"] },
            { emoji: "💜", keywords: ["purple", "heart"] },
            { emoji: "🖤", keywords: ["black", "heart"] },
            { emoji: "🤍", keywords: ["white", "heart"] },
            { emoji: "🤎", keywords: ["brown", "heart"] },
            { emoji: "💯", keywords: ["100", "hundred", "perfect"] },
            { emoji: "💢", keywords: ["anger"] },
            { emoji: "💬", keywords: ["speech", "balloon", "comment"] },
            { emoji: "💭", keywords: ["thought", "balloon"] },
            { emoji: "🗯️", keywords: ["anger", "balloon"] },
            { emoji: "💤", keywords: ["zzz", "sleep"] },
            { emoji: "🔄", keywords: ["refresh", "reload", "repeat"] },
            { emoji: "🔁", keywords: ["repeat", "loop"] },
            { emoji: "🔂", keywords: ["repeat", "one"] },
            { emoji: "▶️", keywords: ["play"] },
            { emoji: "⏩", keywords: ["fast", "forward"] },
            { emoji: "⏭️", keywords: ["next", "track"] },
            { emoji: "⏯️", keywords: ["play", "pause"] },
            { emoji: "◀️", keywords: ["reverse"] },
            { emoji: "⏪", keywords: ["rewind"] },
            { emoji: "⏮️", keywords: ["previous", "track"] },
            { emoji: "🔼", keywords: ["up", "button"] },
            { emoji: "⏫", keywords: ["fast", "up"] },
            { emoji: "🔽", keywords: ["down", "button"] },
            { emoji: "⏬", keywords: ["fast", "down"] },
            { emoji: "⏸️", keywords: ["pause"] },
            { emoji: "⏹️", keywords: ["stop"] },
            { emoji: "⏺️", keywords: ["record"] },
            { emoji: "⏏️", keywords: ["eject"] },
            { emoji: "🎦", keywords: ["cinema", "movie"] },
            { emoji: "🔅", keywords: ["dim", "brightness", "low"] },
            { emoji: "🔆", keywords: ["bright", "high"] },
            { emoji: "📶", keywords: ["signal", "bars"] },
            { emoji: "📳", keywords: ["vibrate", "mode"] },
            { emoji: "📴", keywords: ["mobile", "off"] },
            { emoji: "♀️", keywords: ["female", "woman"] },
            { emoji: "♂️", keywords: ["male", "man"] },
            { emoji: "⚧️", keywords: ["transgender"] },
            { emoji: "✖️", keywords: ["multiply", "x", "cross"] },
            { emoji: "➕", keywords: ["plus", "add"] },
            { emoji: "➖", keywords: ["minus", "subtract"] },
            { emoji: "➗", keywords: ["divide"] },
            { emoji: "🟰", keywords: ["equals", "equal"] },
            { emoji: "♾️", keywords: ["infinity"] },
            { emoji: "‼️", keywords: ["exclamation", "double"] },
            { emoji: "⁉️", keywords: ["exclamation", "question"] },
            { emoji: "❓", keywords: ["question", "what"] },
            { emoji: "❔", keywords: ["question", "white"] },
            { emoji: "❕", keywords: ["exclamation", "white"] },
            { emoji: "❗", keywords: ["exclamation", "red"] },
            { emoji: "〰️", keywords: ["wavy", "dash"] },
            { emoji: "💱", keywords: ["exchange", "currency"] },
            { emoji: "💲", keywords: ["dollar", "money"] },
            { emoji: "⚠️", keywords: ["warning", "caution"] },
            { emoji: "🚸", keywords: ["children", "crossing"] },
            { emoji: "⛔", keywords: ["no", "entry", "forbidden"] },
            { emoji: "🚫", keywords: ["prohibited", "forbidden", "no"] },
            { emoji: "🚳", keywords: ["no", "bicycles"] },
            { emoji: "🚭", keywords: ["no", "smoking"] },
            { emoji: "🚯", keywords: ["no", "litter"] },
            { emoji: "🚱", keywords: ["no", "drinking", "water"] },
            { emoji: "🚷", keywords: ["no", "pedestrians"] },
            { emoji: "📵", keywords: ["no", "phones"] },
            { emoji: "🔞", keywords: ["18", "adult", "restricted"] },
            { emoji: "☢️", keywords: ["radioactive"] },
            { emoji: "☣️", keywords: ["biohazard"] },
            { emoji: "⬆️", keywords: ["up", "arrow"] },
            { emoji: "↗️", keywords: ["up", "right", "arrow"] },
            { emoji: "➡️", keywords: ["right", "arrow"] },
            { emoji: "↘️", keywords: ["down", "right", "arrow"] },
            { emoji: "⬇️", keywords: ["down", "arrow"] },
            { emoji: "↙️", keywords: ["down", "left", "arrow"] },
            { emoji: "⬅️", keywords: ["left", "arrow"] },
            { emoji: "↖️", keywords: ["up", "left", "arrow"] },
            { emoji: "↕️", keywords: ["up", "down", "arrow"] },
            { emoji: "↔️", keywords: ["left", "right", "arrow"] },
            { emoji: "↩️", keywords: ["right", "curve", "arrow"] },
            { emoji: "↪️", keywords: ["left", "curve", "arrow"] },
            { emoji: "⤴️", keywords: ["right", "curve", "up"] },
            { emoji: "⤵️", keywords: ["right", "curve", "down"] },
            { emoji: "🔀", keywords: ["shuffle"] },
            { emoji: "🔁", keywords: ["repeat"] },
            { emoji: "🔘", keywords: ["radio", "button"] },
            { emoji: "🔵", keywords: ["blue", "circle"] },
            { emoji: "🔴", keywords: ["red", "circle"] },
            { emoji: "🟢", keywords: ["green", "circle"] },
            { emoji: "🟡", keywords: ["yellow", "circle"] },
            { emoji: "🟠", keywords: ["orange", "circle"] },
            { emoji: "🟣", keywords: ["purple", "circle"] },
            { emoji: "🟤", keywords: ["brown", "circle"] },
            { emoji: "⚫", keywords: ["black", "circle"] },
            { emoji: "⚪", keywords: ["white", "circle"] },
            { emoji: "🟥", keywords: ["red", "square"] },
            { emoji: "🟧", keywords: ["orange", "square"] },
            { emoji: "🟨", keywords: ["yellow", "square"] },
            { emoji: "🟩", keywords: ["green", "square"] },
            { emoji: "🟦", keywords: ["blue", "square"] },
            { emoji: "🟪", keywords: ["purple", "square"] },
            { emoji: "⬛", keywords: ["black", "square"] },
            { emoji: "⬜", keywords: ["white", "square"] },
            { emoji: "✅", keywords: ["check", "mark", "done", "yes", "ok"] },
            { emoji: "☑️", keywords: ["check", "box"] },
            { emoji: "✔️", keywords: ["check", "mark"] },
            { emoji: "❌", keywords: ["cross", "mark", "no", "wrong", "cancel", "delete"] },
            { emoji: "❎", keywords: ["cross", "mark", "box", "no"] },
            { emoji: "©️", keywords: ["copyright"] },
            { emoji: "®️", keywords: ["registered"] },
            { emoji: "™️", keywords: ["trademark"] },
            { emoji: "#️⃣", keywords: ["hash", "number"] },
            { emoji: "*️⃣", keywords: ["asterisk", "star"] },
            { emoji: "0️⃣", keywords: ["zero", "0"] },
            { emoji: "1️⃣", keywords: ["one", "1"] },
            { emoji: "2️⃣", keywords: ["two", "2"] },
            { emoji: "3️⃣", keywords: ["three", "3"] },
            { emoji: "4️⃣", keywords: ["four", "4"] },
            { emoji: "5️⃣", keywords: ["five", "5"] },
            { emoji: "6️⃣", keywords: ["six", "6"] },
            { emoji: "7️⃣", keywords: ["seven", "7"] },
            { emoji: "8️⃣", keywords: ["eight", "8"] },
            { emoji: "9️⃣", keywords: ["nine", "9"] },
            { emoji: "🔟", keywords: ["ten", "10"] },
            { emoji: "🔠", keywords: ["letters", "uppercase"] },
            { emoji: "🔡", keywords: ["letters", "lowercase"] },
            { emoji: "🔢", keywords: ["numbers"] },
            { emoji: "🔣", keywords: ["symbols"] },
            { emoji: "🔤", keywords: ["abc", "alphabet"] },
            { emoji: "🅰️", keywords: ["a", "blood", "type"] },
            { emoji: "🆎", keywords: ["ab", "blood", "type"] },
            { emoji: "🅱️", keywords: ["b", "blood", "type"] },
            { emoji: "🆑", keywords: ["cl", "clear"] },
            { emoji: "🆒", keywords: ["cool"] },
            { emoji: "🆓", keywords: ["free"] },
            { emoji: "ℹ️", keywords: ["info", "information"] },
            { emoji: "🆔", keywords: ["id"] },
            { emoji: "Ⓜ️", keywords: ["m"] },
            { emoji: "🆕", keywords: ["new"] },
            { emoji: "🆖", keywords: ["ng"] },
            { emoji: "🅾️", keywords: ["o", "blood", "type"] },
            { emoji: "🆗", keywords: ["ok"] },
            { emoji: "🅿️", keywords: ["parking"] },
            { emoji: "🆘", keywords: ["sos", "help", "emergency"] },
            { emoji: "🆙", keywords: ["up"] },
            { emoji: "🆚", keywords: ["vs", "versus"] },
            { emoji: "🈁", keywords: ["koko", "here"] },
            { emoji: "🈂️", keywords: ["sa", "service"] },
            { emoji: "🈷️", keywords: ["month"] },
            { emoji: "🈶", keywords: ["have"] },
            { emoji: "🈯", keywords: ["point"] },
            { emoji: "🉐", keywords: ["gain"] },
            { emoji: "🈹", keywords: ["discount"] },
            { emoji: "🈚", keywords: ["nothing", "none"] },
            { emoji: "🈲", keywords: ["prohibited"] },
            { emoji: "🉑", keywords: ["acceptable"] },
            { emoji: "🈸", keywords: ["application"] },
            { emoji: "🈴", keywords: ["passing"] },
            { emoji: "🈳", keywords: ["empty", "vacancy"] },
            { emoji: "㊗️", keywords: ["congratulations"] },
            { emoji: "㊙️", keywords: ["secret"] },
            { emoji: "🈺", keywords: ["open", "for", "business"] },
            { emoji: "🈵", keywords: ["full"] },
            { emoji: "🔴", keywords: ["red"] },
            { emoji: "🟠", keywords: ["orange"] },
            { emoji: "🟡", keywords: ["yellow"] },
            { emoji: "🟢", keywords: ["green"] },
            { emoji: "🔵", keywords: ["blue"] },
            { emoji: "🟣", keywords: ["purple"] },
            { emoji: "🟤", keywords: ["brown"] },
            { emoji: "🖤", keywords: ["black"] },
            { emoji: "🤍", keywords: ["white"] },
            { emoji: "🩶", keywords: ["grey", "gray"] },
        ]
    },
    {
        name: "Flags",
        icon: "🏁",
        emojis: [
            { emoji: "🏁", keywords: ["checkered", "flag", "finish", "race"] },
            { emoji: "🚩", keywords: ["triangular", "flag"] },
            { emoji: "🎌", keywords: ["crossed", "flags"] },
            { emoji: "🏴", keywords: ["black", "flag"] },
            { emoji: "🏳️", keywords: ["white", "flag", "surrender"] },
            { emoji: "🏳️‍🌈", keywords: ["rainbow", "flag", "pride", "lgbt"] },
            { emoji: "🏳️‍⚧️", keywords: ["transgender", "flag"] },
            { emoji: "🏴‍☠️", keywords: ["pirate", "flag"] },
            { emoji: "🇺🇸", keywords: ["us", "usa", "united", "states", "america"] },
            { emoji: "🇬🇧", keywords: ["uk", "united", "kingdom", "britain"] },
            { emoji: "🇨🇦", keywords: ["canada", "canadian"] },
            { emoji: "🇦🇺", keywords: ["australia", "australian"] },
            { emoji: "🇳🇿", keywords: ["new", "zealand"] },
            { emoji: "🇮🇪", keywords: ["ireland", "irish"] },
            { emoji: "🇯🇵", keywords: ["japan", "japanese"] },
            { emoji: "🇰🇷", keywords: ["korea", "south", "korean"] },
            { emoji: "🇨🇳", keywords: ["china", "chinese"] },
            { emoji: "🇹🇼", keywords: ["taiwan", "taiwanese"] },
            { emoji: "🇭🇰", keywords: ["hong", "kong"] },
            { emoji: "🇮🇳", keywords: ["india", "indian"] },
            { emoji: "🇵🇰", keywords: ["pakistan"] },
            { emoji: "🇧🇩", keywords: ["bangladesh"] },
            { emoji: "🇹🇭", keywords: ["thailand"] },
            { emoji: "🇻🇳", keywords: ["vietnam"] },
            { emoji: "🇵🇭", keywords: ["philippines"] },
            { emoji: "🇲🇾", keywords: ["malaysia"] },
            { emoji: "🇸🇬", keywords: ["singapore"] },
            { emoji: "🇮🇩", keywords: ["indonesia"] },
            { emoji: "🇩🇪", keywords: ["germany", "german"] },
            { emoji: "🇫🇷", keywords: ["france", "french"] },
            { emoji: "🇮🇹", keywords: ["italy", "italian"] },
            { emoji: "🇪🇸", keywords: ["spain", "spanish"] },
            { emoji: "🇵🇹", keywords: ["portugal", "portuguese"] },
            { emoji: "🇳🇱", keywords: ["netherlands", "dutch"] },
            { emoji: "🇧🇪", keywords: ["belgium"] },
            { emoji: "🇨🇭", keywords: ["switzerland", "swiss"] },
            { emoji: "🇦🇹", keywords: ["austria"] },
            { emoji: "🇸🇪", keywords: ["sweden"] },
            { emoji: "🇳🇴", keywords: ["norway"] },
            { emoji: "🇩🇰", keywords: ["denmark"] },
            { emoji: "🇫🇮", keywords: ["finland"] },
            { emoji: "🇵🇱", keywords: ["poland"] },
            { emoji: "🇺🇦", keywords: ["ukraine"] },
            { emoji: "🇷🇺", keywords: ["russia", "russian"] },
            { emoji: "🇹🇷", keywords: ["turkey", "turkish"] },
            { emoji: "🇬🇷", keywords: ["greece"] },
            { emoji: "🇧🇷", keywords: ["brazil", "brazilian"] },
            { emoji: "🇲🇽", keywords: ["mexico", "mexican"] },
            { emoji: "🇦🇷", keywords: ["argentina"] },
            { emoji: "🇨🇱", keywords: ["chile"] },
            { emoji: "🇨🇴", keywords: ["colombia"] },
            { emoji: "🇵🇪", keywords: ["peru"] },
            { emoji: "🇪🇬", keywords: ["egypt"] },
            { emoji: "🇿🇦", keywords: ["south", "africa"] },
            { emoji: "🇳🇬", keywords: ["nigeria"] },
            { emoji: "🇰🇪", keywords: ["kenya"] },
            { emoji: "🇮🇱", keywords: ["israel"] },
            { emoji: "🇸🇦", keywords: ["saudi", "arabia"] },
            { emoji: "🇦🇪", keywords: ["uae", "emirates"] },
            { emoji: "🇶🇦", keywords: ["qatar"] },
            { emoji: "🇰🇼", keywords: ["kuwait"] },
            { emoji: "🇮🇷", keywords: ["iran"] },
            { emoji: "🇮🇶", keywords: ["iraq"] },
            { emoji: "🇸🇾", keywords: ["syria"] },
            { emoji: "🇱🇧", keywords: ["lebanon"] },
            { emoji: "🇯🇴", keywords: ["jordan"] },
            { emoji: "🇪🇺", keywords: ["european", "union", "eu"] },
            { emoji: "🇺🇳", keywords: ["united", "nations", "un"] },
        ]
    },
];
