// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearHistory():Promise<void>;

export function GetClips():Promise<Array<string>>;

export function HideWindow():Promise<void>;

export function SelectClip(arg1:string):Promise<void>;
