// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function GetClips() {
  return window['go']['main']['App']['GetClips']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function SelectClip(arg1) {
  return window['go']['main']['App']['SelectClip'](arg1);
}
