// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearHistory():Promise<void>;

export function DeleteClip(arg1:string):Promise<void>;

export function GetClips():Promise<Record<string, any>>;

export function GetEditorText():Promise<string>;

export function GetSnippetContent(arg1:string):Promise<string>;

export function GetSnippetThumbnail(arg1:string):Promise<string>;

export function GetSnippets():Promise<Array<main.Snippet>>;

export function HideWindow():Promise<void>;

export function PasteSnippetImage(arg1:string):Promise<void>;

export function PinClip(arg1:string):Promise<void>;

export function SelectClip(arg1:string):Promise<void>;

export function SelectSnippet(arg1:string):Promise<void>;

export function SetEditorText(arg1:string):Promise<void>;

export function UnpinClip(arg1:string):Promise<void>;
